### ISSUE TITLE
自动提交价格前，数据采样是对的，伏击出价时，价格就不对了

### ISSUE THREAD

**Issue by avichen** [embest/HupaiBid#1]
使用http://moni.51hupai.com/模拟
以下是屏幕日志数据：
时间：11:29:41 价格：:87500
伏击出价：1200
价格已输入，等待验证码
时间：11:29:42 价格：:87600
时间：11:29:43 价格：:87600
时间：11:29:44 价格：:87600
不检测验证码
时间：11:29:45 价格：:87600
时间：11:29:46 价格：:87600
时间：11:29:47 价格：:87600
验证码输入：1291
采样1：11:29:48 价格：0

提交时，就只提交了￥1200

**Comment by embest** [comment]
看起来应该是屏幕采样坐标错了。 请参照常见问题1改改试试。如果不行，把软件目录下debug文件夹（如果有）压缩，及最新时间的zip文件（如:bid_2018_0618_220625.zip）传上来看看。

**Comment by avichen** [comment]
给我个邮箱吧，我发给你debug

**Comment by embest** [comment]
放个网盘链接吧。更方便。

**Comment by avichen** [comment]
链接: https://pan.baidu.com/s/1XjXlgkbav0GIMtkw3fAKVA 密码: wnbp

**Comment by embest** [comment]
屏幕采样坐标错了。请参照常见问题1，修改采样坐标。设置->价格偏移X，当前值+2， 时间偏移X，当前值 +1。

**Comment by jinwyp** [comment]
这个屏幕校准怎么弄啊， 到底调多少怎么能看出来， 还有 win10下不能用吗？
