### ISSUE TITLE
这个屏幕校准怎么弄啊， 到底调多少怎么能看出来， ？

### ISSUE THREAD

**Issue by jinwyp** [embest/HupaiBid#3]
这个屏幕校准怎么弄啊， 到底调多少怎么能看出来， 还有 win10下不能用吗？

还有IE是不是要最大化？

感觉不知道怎么调整。

价格偏移x和y 是相对于哪个点的偏移啊？

能不能改成直接用鼠标选点的模式， 

价格偏移是指哪个点？ “最低可成交价: ”这个行吗？
时间偏移是指哪个点？“系统目前时间” 这个航妈？

**Comment by embest** [comment]
Win10下面目前应该是不能用的。我没有测试过。
IE 可以不用最大化，但是不能有缩放。
XY是指左上角坐标。
价格偏移：目前最低可成交价
时间：系统目前时间
